In [1]:
from faker import Faker
import pandas as pd
import random
from datetime import datetime, timedelta

fake = Faker("en_IN")
random.seed(42)

In [2]:
print("Notebook is working successfully!")

Notebook is working successfully!

In [3]:
NUM_CUSTOMERS = 5000

In [50]:
customers = []

connection_types = ["Prepaid", "Postpaid"]
plan_names = ["Basic 199", "Unlimited 399", "Family 699", "Premium 999"]
statuses = ["Active", "Inactive", "Suspended"]

for i in range(1, NUM_CUSTOMERS + 1):
    customers.append({
        "customer_id": f"CUST{i:05d}",
        "first_name": fake.first_name(),
        "last_name": fake.last_name(),
        "mobile_number": "9" + "".join(str(random.randint(0, 9)) for _ in range(9)),
        "email": fake.email(),
        "city": fake.city(),
        "state": fake.state(),
        "connection_type": random.choice(connection_types),
        "plan_name": random.choice(plan_names),
        "account_status": random.choice(statuses),
        "created_at": fake.date_time_between(start_date="-5y", end_date="now")
    })

customer_df = pd.DataFrame(customers)

customer_df.head()

,customer_id,first_name,last_name,mobile_number,email,city,state,connection_type,plan_name,account_status,created_at
0,CUST00001,Imaran,Malhotra,9076954504,darika26@example.com,Patiala,Haryana,Postpaid,Basic 199,Inactive,2024-07-11 18:44:22
1,CUST00002,Jacob,Agrawal,9809242619,klal@example.org,Gaya,Rajasthan,Postpaid,Premium 999,Active,2022-09-10 10:07:30
2,CUST00003,Dalbir,Soman,9375102208,bhanumati34@example.org,Meerut,Meghalaya,Postpaid,Family 699,Inactive,2024-05-31 18:01:37
3,CUST00004,Anita,Dara,9928829289,adyamahal@example.com,Jalgaon,Goa,Postpaid,Unlimited 399,Active,2023-12-19 09:02:12
4,CUST00005,Pranav,Malhotra,9479139549,darsh95@example.org,Jorhat,Nagaland,Postpaid,Unlimited 399,Inactive,2021-11-29 23:49:41

In [51]:
customer_df.to_csv("../data/customer_master.csv", index=False)

print("customer_master.csv created successfully!")

customer_master.csv created successfully!

In [ ]:
mobile_connections = []

network_types = ["4G", "5G"]
sim_types = ["Prepaid", "Postpaid"]
statuses = ["Active", "Inactive", "Suspended"]

for customer_id, mobile_number in zip(customer_df["customer_id"], customer_df["mobile_number"]):
    mobile_connections.append({
        "customer_id": customer_id,
        "sim_number": "89" + "".join(str(random.randint(0, 9)) for _ in range(18)),
        "mobile_number": mobile_number,
        "network_type": random.choice(network_types),
        "sim_type": random.choice(sim_types),
        "activation_date": fake.date_between(start_date="-5y", end_date="today"),
        "status": random.choice(statuses)
    })

mobile_df = pd.DataFrame(mobile_connections)

mobile_df.head()

,customer_id,sim_number,mobile_number,network_type,sim_type,activation_date,status
0,CUST00001,89599803752303931102,9202730238,5G,Postpaid,2022-06-17,Active
1,CUST00002,89179582522299118400,9129207223,4G,Postpaid,2021-09-12,Active
2,CUST00003,89074346481868425637,9582339895,5G,Prepaid,2024-12-01,Suspended
3,CUST00004,89805285096568651890,9139977387,4G,Postpaid,2022-03-30,Inactive
4,CUST00005,89232388776939980682,9767823608,4G,Prepaid,2025-11-12,Active

In [9]:
mobile_df.to_csv("../data/mobile_connections.csv", index=False)

print("mobile_connections.csv created successfully!")

mobile_connections.csv created successfully!

In [10]:
customer_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   customer_id      5000 non-null   str
 1   first_name       5000 non-null   str
 2   last_name        5000 non-null   str
 3   mobile_number    5000 non-null   str
 4   email            5000 non-null   str
 5   city             5000 non-null   str
 6   state            5000 non-null   str
 7   connection_type  5000 non-null   str
 8   plan_name        5000 non-null   str
 9   account_status   5000 non-null   str
 10  created_at       5000 non-null   datetime64[us]
dtypes: datetime64[us](1), str(10)
memory usage: 429.8 KB

In [13]:
customer_df["customer_id"].duplicated().sum()

np.int64(0)

In [14]:
customer_df["mobile_number"].duplicated().sum()

np.int64(0)

In [15]:
customer_df.isnull().sum()

customer_id        0
first_name         0
last_name          0
mobile_number      0
email              0
city               0
state              0
connection_type    0
plan_name          0
account_status     0
created_at         0
dtype: int64

In [16]:
plans = [
    {
        "plan_name": "Basic 199",
        "service_type": "Mobile",
        "monthly_price": 199,
        "data_limit_gb": 2,
        "validity_days": 28,
        "speed_mbps": None,
        "voice_minutes": "Unlimited",
        "sms_limit": 100,
        "status": "Active"
    },
    {
        "plan_name": "Unlimited 399",
        "service_type": "Mobile",
        "monthly_price": 399,
        "data_limit_gb": 3,
        "validity_days": 28,
        "speed_mbps": None,
        "voice_minutes": "Unlimited",
        "sms_limit": 100,
        "status": "Active"
    },
    {
        "plan_name": "Family 699",
        "service_type": "Mobile",
        "monthly_price": 699,
        "data_limit_gb": 5,
        "validity_days": 30,
        "speed_mbps": None,
        "voice_minutes": "Unlimited",
        "sms_limit": 100,
        "status": "Active"
    },
    {
        "plan_name": "Premium 999",
        "service_type": "Broadband",
        "monthly_price": 999,
        "data_limit_gb": None,
        "validity_days": 30,
        "speed_mbps": 200,
        "voice_minutes": "N/A",
        "sms_limit": None,
        "status": "Active"
    }
]

plans_df = pd.DataFrame(plans)

plans_df.head()

,plan_name,service_type,monthly_price,data_limit_gb,validity_days,speed_mbps,voice_minutes,sms_limit,status
0,Basic 199,Mobile,199,2.0,28,NaN,Unlimited,100.0,Active
1,Unlimited 399,Mobile,399,3.0,28,NaN,Unlimited,100.0,Active
2,Family 699,Mobile,699,5.0,30,NaN,Unlimited,100.0,Active
3,Premium 999,Broadband,999,NaN,30,200.0,N/A,NaN,Active

In [18]:
plans = [
    ["Basic 199","Mobile",199,2,28,None,"Unlimited",100,"Active"],
    ["Value 249","Mobile",249,3,28,None,"Unlimited",100,"Active"],
    ["Smart 299","Mobile",299,2,30,None,"Unlimited",100,"Active"],
    ["Unlimited 399","Mobile",399,3,28,None,"Unlimited",100,"Active"],
    ["5G Max 499","Mobile",499,4,28,None,"Unlimited",100,"Active"],
    ["Entertainment 599","Mobile",599,5,28,None,"Unlimited",100,"Active"],
    ["Family 699","Mobile",699,6,30,None,"Unlimited",100,"Active"],
    ["Premium 799","Mobile",799,8,30,None,"Unlimited",100,"Active"],
    ["Elite 999","Mobile",999,10,30,None,"Unlimited",100,"Active"],
    ["Business 1499","Mobile",1499,15,30,None,"Unlimited",100,"Active"],

    ["Fiber 499","Broadband",499,None,30,40,"N/A",None,"Active"],
    ["Fiber 699","Broadband",699,None,30,100,"N/A",None,"Active"],
    ["Fiber 799","Broadband",799,None,30,150,"N/A",None,"Active"],
    ["Fiber 999","Broadband",999,None,30,200,"N/A",None,"Active"],
    ["Fiber 1499","Broadband",1499,None,30,300,"N/A",None,"Active"],
    ["Fiber 1999","Broadband",1999,None,30,500,"N/A",None,"Active"],
    ["Fiber 2499","Broadband",2499,None,30,1000,"N/A",None,"Active"],

    ["Enterprise 2999","Enterprise",2999,None,30,500,"Unlimited",None,"Active"],
    ["Enterprise 4999","Enterprise",4999,None,30,1000,"Unlimited",None,"Active"],
    ["Enterprise 9999","Enterprise",9999,None,30,2000,"Unlimited",None,"Active"]
]

plans_df = pd.DataFrame(
    plans,
    columns=[
        "plan_name",
        "service_type",
        "monthly_price",
        "data_limit_gb",
        "validity_days",
        "speed_mbps",
        "voice_minutes",
        "sms_limit",
        "status"
    ]
)

plans_df.head()

,plan_name,service_type,monthly_price,data_limit_gb,validity_days,speed_mbps,voice_minutes,sms_limit,status
0,Basic 199,Mobile,199,2.0,28,NaN,Unlimited,100.0,Active
1,Value 249,Mobile,249,3.0,28,NaN,Unlimited,100.0,Active
2,Smart 299,Mobile,299,2.0,30,NaN,Unlimited,100.0,Active
3,Unlimited 399,Mobile,399,3.0,28,NaN,Unlimited,100.0,Active
4,5G Max 499,Mobile,499,4.0,28,NaN,Unlimited,100.0,Active

In [19]:
plans_df.to_csv("../data/plans_tariffs.csv", index=False)

print("plans_tariffs.csv created successfully!")

plans_tariffs.csv created successfully!

In [20]:
# Customers who have broadband (about 50%)
broadband_customers = customer_df.sample(n=2500, random_state=42)

broadband_plans = [
    "Fiber 499",
    "Fiber 699",
    "Fiber 799",
    "Fiber 999",
    "Fiber 1499",
    "Fiber 1999",
    "Fiber 2499"
]

speed_mapping = {
    "Fiber 499": 40,
    "Fiber 699": 100,
    "Fiber 799": 150,
    "Fiber 999": 200,
    "Fiber 1499": 300,
    "Fiber 1999": 500,
    "Fiber 2499": 1000
}

statuses = ["Active", "Inactive", "Suspended"]

broadband_data = []

for i, row in enumerate(broadband_customers.itertuples(index=False), start=1):
    plan = random.choice(broadband_plans)

    broadband_data.append({
        "customer_id": row.customer_id,
        "connection_number": f"BB{i:08d}",
        "broadband_plan": plan,
        "connection_type": "Fiber",
        "speed_mbps": speed_mapping[plan],
        "installation_date": fake.date_between(start_date="-5y", end_date="today"),
        "status": random.choice(statuses)
    })

broadband_df = pd.DataFrame(broadband_data)

broadband_df.head()

,customer_id,connection_number,broadband_plan,connection_type,speed_mbps,installation_date,status
0,CUST01502,BB00000001,Fiber 2499,Fiber,1000,2022-05-08,Active
1,CUST02587,BB00000002,Fiber 2499,Fiber,1000,2024-03-12,Inactive
2,CUST02654,BB00000003,Fiber 999,Fiber,200,2023-06-26,Inactive
3,CUST01056,BB00000004,Fiber 799,Fiber,150,2021-12-05,Suspended
4,CUST00706,BB00000005,Fiber 799,Fiber,150,2023-06-16,Suspended

In [21]:
broadband_df.to_csv("../data/broadband_connections.csv", index=False)

print("broadband_connections.csv created successfully!")

broadband_connections.csv created successfully!

In [22]:
broadband_df.duplicated().sum()

np.int64(0)

In [23]:
broadband_df.isnull().sum()

customer_id          0
connection_number    0
broadband_plan       0
connection_type      0
speed_mbps           0
installation_date    0
status               0
dtype: int64

In [ ]:
billing_data = []

payment_statuses = ["Paid", "Paid", "Paid", "Pending", "Overdue"]

for customer in customer_df.itertuples(index=False):

    for month in range(12):   # 12 months of billing

        bill_month = fake.date_between(start_date="-12M", end_date="today")

        if customer.plan_name == "Basic 199":
            amount = 199
        elif customer.plan_name == "Unlimited 399":
            amount = 399
        elif customer.plan_name == "Family 699":
            amount = 699
        elif customer.plan_name == "Premium 999":
            amount = 999
        else:
            amount = random.choice([199,299,399,499,699,999])

        late_fee = random.choice([0,0,0,25,50,100])

        payment_status = random.choice(payment_statuses)

        billing_data.append({
            "customer_id": customer.customer_id,
            "bill_month": bill_month,
            "bill_amount": amount,
            "due_date": bill_month + timedelta(days=15),
            "payment_date": bill_month + timedelta(days=random.randint(0,20)),
            "payment_status": payment_status,
            "late_fee": late_fee,
            "total_amount": amount + late_fee
        })

billing_df = pd.DataFrame(billing_data)

billing_df.head()

,customer_id,bill_month,bill_amount,due_date,payment_date,payment_status,late_fee,total_amount
0,CUST00001,2026-06-07,699,2026-06-22,2026-06-20,Paid,100,799
1,CUST00001,2026-01-26,699,2026-02-10,2026-02-01,Paid,0,699
2,CUST00001,2026-01-07,699,2026-01-22,2026-01-17,Paid,50,749
3,CUST00001,2026-01-20,699,2026-02-04,2026-01-25,Overdue,50,749
4,CUST00001,2025-07-09,699,2025-07-24,2025-07-20,Paid,0,699

In [25]:
billing_df.to_csv("../data/billing_history.csv", index=False)

print("billing_history.csv created successfully!")

billing_history.csv created successfully!

In [26]:
billing_df.isnull().sum()

customer_id       0
bill_month        0
bill_amount       0
due_date          0
payment_date      0
payment_status    0
late_fee          0
total_amount      0
dtype: int64

In [27]:
recharge_data = []

payment_methods = [
    "UPI",
    "Credit Card",
    "Debit Card",
    "Net Banking",
    "Wallet"
]

transaction_statuses = [
    "Success",
    "Success",
    "Success",
    "Pending",
    "Failed"
]

recharge_amounts = [199, 249, 299, 399, 499, 699, 999, 1499]

for customer in customer_df.itertuples(index=False):

    num_transactions = random.randint(8, 20)

    for _ in range(num_transactions):

        recharge_data.append({
            "customer_id": customer.customer_id,
            "recharge_date": fake.date_time_between(start_date="-2y", end_date="now"),
            "amount": random.choice(recharge_amounts),
            "payment_method": random.choice(payment_methods),
            "transaction_status": random.choice(transaction_statuses),
            "reference_number": fake.unique.bothify(text="TXN##########")
        })

recharge_df = pd.DataFrame(recharge_data)

recharge_df.head()

,customer_id,recharge_date,amount,payment_method,transaction_status,reference_number
0,CUST00001,2024-11-30 03:48:23,399,Credit Card,Failed,TXN8553086576
1,CUST00001,2026-02-12 09:34:57,399,Wallet,Success,TXN4014496477
2,CUST00001,2025-06-23 07:25:52,399,Wallet,Success,TXN4974451490
3,CUST00001,2026-01-26 21:38:15,699,Wallet,Success,TXN8056919680
4,CUST00001,2025-05-16 05:42:57,249,Debit Card,Success,TXN4340168261

In [28]:
recharge_df.to_csv("../data/recharge_transactions.csv", index=False)

print("recharge_transactions.csv created successfully!")

recharge_transactions.csv created successfully!

In [29]:
service_requests = []

request_types = [
    "SIM Activation",
    "Broadband Installation",
    "Plan Change",
    "Network Issue",
    "Bill Dispute",
    "Address Update",
    "Fiber Upgrade",
    "SIM Replacement",
    "Service Cancellation",
    "New Connection"
]

statuses = ["Open", "In Progress", "Resolved", "Closed"]

priorities = ["Low", "Medium", "High", "Critical"]

agents = [
    "Rahul Sharma",
    "Priya Reddy",
    "Amit Kumar",
    "Sneha Patel",
    "Arjun Singh",
    "Neha Verma",
    "Rohit Rao",
    "Kiran Das"
]

for customer in customer_df.itertuples(index=False):

    for _ in range(random.randint(1,4)):

        request_date = fake.date_time_between(start_date="-2y", end_date="now")

        status = random.choice(statuses)

        resolution_date = (
            request_date + timedelta(days=random.randint(1,10))
            if status in ["Resolved","Closed"] else None
        )

        service_requests.append({
            "customer_id": customer.customer_id,
            "request_type": random.choice(request_types),
            "request_date": request_date,
            "status": status,
            "priority": random.choice(priorities),
            "assigned_to": random.choice(agents),
            "resolution_date": resolution_date
        })

service_df = pd.DataFrame(service_requests)

service_df.head()

,customer_id,request_type,request_date,status,priority,assigned_to,resolution_date
0,CUST00001,Plan Change,2025-07-17 19:46:10,Resolved,Medium,Rohit Rao,2025-07-20 19:46:10
1,CUST00001,Fiber Upgrade,2024-12-13 04:01:58,Resolved,Medium,Arjun Singh,2024-12-19 04:01:58
2,CUST00001,New Connection,2025-04-22 11:28:48,Open,Low,Rahul Sharma,NaT
3,CUST00001,Fiber Upgrade,2026-01-10 15:33:10,In Progress,Critical,Sneha Patel,NaT
4,CUST00002,SIM Activation,2025-10-06 15:18:31,In Progress,Medium,Arjun Singh,NaT

In [30]:
service_df.to_csv("../data/service_requests.csv", index=False)

print("service_requests.csv created successfully!")

service_requests.csv created successfully!

In [35]:
complaints = []

categories = [
    "Network Issue",
    "Billing Issue",
    "Slow Internet",
    "Call Drop",
    "SIM Activation",
    "Recharge Failure",
    "Fiber Issue",
    "Plan Change",
    "Service Quality"
]

statuses = ["Open", "In Progress", "Resolved", "Closed"]

for request_id, request in enumerate(service_df.itertuples(index=False), start=1):

    if random.random() < 0.6:

        complaint_date = request.request_date

        resolved_date = (
            complaint_date + timedelta(days=random.randint(1, 7))
            if request.status in ["Resolved", "Closed"] else None
        )

        complaints.append({
            "customer_id": request.customer_id,
            "request_id": request_id,
            "complaint_category": random.choice(categories),
            "complaint_description": fake.sentence(nb_words=10),
            "complaint_date": complaint_date,
            "status": request.status,
            "resolution_notes": fake.sentence(nb_words=12) if resolved_date else None,
            "resolved_date": resolved_date
        })

complaint_df = pd.DataFrame(complaints)

complaint_df.head()

,customer_id,request_id,complaint_category,complaint_description,complaint_date,status,resolution_notes,resolved_date
0,CUST00001,1,Recharge Failure,Porro ullam aliquam modi tempora tempora ut.,2025-07-17 19:46:10,Resolved,Cupiditate officiis explicabo voluptatum susci...,2025-07-21 19:46:10
1,CUST00001,3,Fiber Issue,Reprehenderit nulla commodi mollitia ipsum max...,2025-04-22 11:28:48,Open,NaN,NaT
2,CUST00001,4,Plan Change,Enim assumenda odio quisquam porro illo numqua...,2026-01-10 15:33:10,In Progress,NaN,NaT
3,CUST00002,5,Network Issue,Officiis molestiae dolorem distinctio sapiente...,2025-10-06 15:18:31,In Progress,NaN,NaT
4,CUST00004,9,Network Issue,Natus quae sequi doloremque reprehenderit omni...,2024-09-05 02:00:22,In Progress,NaN,NaT

In [36]:
complaint_df.to_csv("../data/complaint_tickets.csv", index=False)

print("complaint_tickets.csv created successfully!")

complaint_tickets.csv created successfully!

In [37]:
tower_data = []

cities = [
    ("Bengaluru","Karnataka"),
    ("Hyderabad","Telangana"),
    ("Chennai","Tamil Nadu"),
    ("Mumbai","Maharashtra"),
    ("Delhi","Delhi"),
    ("Pune","Maharashtra"),
    ("Kolkata","West Bengal"),
    ("Ahmedabad","Gujarat"),
    ("Jaipur","Rajasthan"),
    ("Lucknow","Uttar Pradesh")
]

network_types = ["4G", "5G"]
statuses = ["Active", "Maintenance", "Inactive"]

for i in range(1, 101):

    city, state = random.choice(cities)

    tower_data.append({
        "tower_code": f"TWR{i:04d}",
        "tower_name": f"{city} Tower {i}",
        "city": city,
        "state": state,
        "network_type": random.choice(network_types),
        "latitude": round(random.uniform(8.0, 37.0), 6),
        "longitude": round(random.uniform(68.0, 97.0), 6),
        "status": random.choice(statuses)
    })

tower_df = pd.DataFrame(tower_data)

tower_df.head()

,tower_code,tower_name,city,state,network_type,latitude,longitude,status
0,TWR0001,Kolkata Tower 1,Kolkata,West Bengal,5G,15.955855,80.595867,Active
1,TWR0002,Bengaluru Tower 2,Bengaluru,Karnataka,5G,14.881097,76.288183,Maintenance
2,TWR0003,Mumbai Tower 3,Mumbai,Maharashtra,4G,19.568343,94.698249,Maintenance
3,TWR0004,Hyderabad Tower 4,Hyderabad,Telangana,5G,29.049607,93.163826,Active
4,TWR0005,Kolkata Tower 5,Kolkata,West Bengal,4G,31.609846,74.596191,Inactive

In [38]:
tower_df.to_csv("../data/network_towers.csv", index=False)

print("network_towers.csv created successfully!")

network_towers.csv created successfully!

In [39]:
outage_data = []

outage_types = [
    "Power Failure",
    "Fiber Cut",
    "Network Congestion",
    "Hardware Failure",
    "Software Upgrade",
    "Weather Impact"
]

areas = [
    "North Zone",
    "South Zone",
    "East Zone",
    "West Zone",
    "Central Zone"
]

statuses = ["Resolved", "Resolved", "Resolved", "Ongoing"]

for _ in range(300):

    start_time = fake.date_time_between(start_date="-1y", end_date="now")

    status = random.choice(statuses)

    end_time = (
        start_time + timedelta(hours=random.randint(1, 12))
        if status == "Resolved"
        else None
    )

    outage_data.append({
        "tower_id": random.randint(1, len(tower_df)),
        "outage_type": random.choice(outage_types),
        "affected_area": random.choice(areas),
        "start_time": start_time,
        "end_time": end_time,
        "outage_status": status,
        "root_cause": fake.sentence(nb_words=8)
    })

outage_df = pd.DataFrame(outage_data)

outage_df.head()

,tower_id,outage_type,affected_area,start_time,end_time,outage_status,root_cause
0,28,Power Failure,West Zone,2026-05-17 01:04:59,2026-05-17 10:04:59,Resolved,Voluptate soluta ipsam rem earum expedita temp...
1,54,Network Congestion,North Zone,2025-08-29 07:31:52,2025-08-29 19:31:52,Resolved,Quam quia reprehenderit consectetur et vitae s...
2,92,Weather Impact,West Zone,2025-08-27 10:25:04,2025-08-27 12:25:04,Resolved,Dolores molestiae in nostrum nostrum ab iusto ...
3,98,Hardware Failure,Central Zone,2025-11-04 15:37:22,2025-11-05 02:37:22,Resolved,Vero error eum sed quasi esse porro quis moles...
4,46,Hardware Failure,North Zone,2025-11-06 06:20:03,NaT,Ongoing,Dolorum ad consequatur laboriosam delectus com...

In [40]:
outage_data = []

outage_types = [
    "Power Failure",
    "Fiber Cut",
    "Network Congestion",
    "Hardware Failure",
    "Software Upgrade",
    "Weather Impact"
]

areas = [
    "North Zone",
    "South Zone",
    "East Zone",
    "West Zone",
    "Central Zone"
]

statuses = ["Resolved", "Resolved", "Resolved", "Ongoing"]

for _ in range(300):

    start_time = fake.date_time_between(start_date="-1y", end_date="now")

    status = random.choice(statuses)

    end_time = (
        start_time + timedelta(hours=random.randint(1, 12))
        if status == "Resolved"
        else None
    )

    outage_data.append({
        "tower_id": random.randint(1, len(tower_df)),
        "outage_type": random.choice(outage_types),
        "affected_area": random.choice(areas),
        "start_time": start_time,
        "end_time": end_time,
        "outage_status": status,
        "root_cause": fake.sentence(nb_words=8)
    })

outage_df = pd.DataFrame(outage_data)

outage_df.head()

,tower_id,outage_type,affected_area,start_time,end_time,outage_status,root_cause
0,87,Network Congestion,North Zone,2026-03-25 09:51:26,2026-03-25 16:51:26,Resolved,Similique quae architecto suscipit aliquam cor...
1,68,Weather Impact,North Zone,2026-03-16 08:44:13,2026-03-16 19:44:13,Resolved,Ducimus voluptates odio sequi quas natus vitae...
2,44,Software Upgrade,West Zone,2025-09-19 22:34:37,2025-09-20 05:34:37,Resolved,Dolor accusamus aliquid numquam non.
3,31,Weather Impact,West Zone,2025-07-05 11:50:36,2025-07-05 18:50:36,Resolved,Culpa asperiores adipisci animi ducimus rem.
4,13,Network Congestion,North Zone,2026-03-18 06:02:32,NaT,Ongoing,Eveniet dolorem fugit et voluptates doloribus.

In [41]:
outage_df.to_csv("../data/outage_reports.csv", index=False)

print("outage_reports.csv created successfully!")

outage_reports.csv created successfully!

In [42]:
activation_data = []

activation_statuses = ["Activated", "Activated", "Activated", "Pending", "Failed"]
kyc_statuses = ["Verified", "Verified", "Pending", "Rejected"]

employees = [
    "EMP101",
    "EMP102",
    "EMP103",
    "EMP104",
    "EMP105",
    "EMP106",
    "EMP107",
    "EMP108"
]

for mobile in mobile_df.itertuples(index=False):

    activation_data.append({
        "customer_id": mobile.customer_id,
        "sim_number": mobile.sim_number,
        "activation_date": fake.date_time_between(start_date="-2y", end_date="now"),
        "activation_status": random.choice(activation_statuses),
        "kyc_status": random.choice(kyc_statuses),
        "activated_by": random.choice(employees)
    })

activation_df = pd.DataFrame(activation_data)

activation_df.head()

,customer_id,sim_number,activation_date,activation_status,kyc_status,activated_by
0,CUST00001,89599803752303931102,2024-07-04 12:57:44,Failed,Pending,EMP108
1,CUST00002,89179582522299118400,2025-10-05 10:55:40,Activated,Verified,EMP102
2,CUST00003,89074346481868425637,2026-04-04 05:52:30,Failed,Rejected,EMP106
3,CUST00004,89805285096568651890,2024-07-08 00:51:12,Pending,Pending,EMP103
4,CUST00005,89232388776939980682,2026-05-19 04:21:18,Activated,Rejected,EMP107

In [43]:
activation_df.to_csv("../data/sim_activation_records.csv", index=False)

print("sim_activation_records.csv created successfully!")

sim_activation_records.csv created successfully!

In [44]:
engineers_data = []

specializations = [
    "Fiber Installation",
    "Network Support",
    "SIM Activation",
    "Broadband Maintenance",
    "Field Support"
]

regions = [
    "Bengaluru",
    "Hyderabad",
    "Chennai",
    "Mumbai",
    "Delhi",
    "Pune",
    "Kolkata",
    "Ahmedabad"
]

statuses = ["Active", "On Leave", "Inactive"]

for i in range(1, 101):

    engineers_data.append({
        "engineer_name": fake.name(),
        "employee_id": f"EMP{i:04d}",
        "specialization": random.choice(specializations),
        "mobile_number": "9" + "".join(str(random.randint(0,9)) for _ in range(9)),
        "email": fake.email(),
        "assigned_region": random.choice(regions),
        "status": random.choice(statuses)
    })

engineers_df = pd.DataFrame(engineers_data)

engineers_df.head()

,engineer_name,employee_id,specialization,mobile_number,email,assigned_region,status
0,Ishaan Sarma,EMP0001,Fiber Installation,9375863182,nitara63@example.org,Mumbai,Inactive
1,Fariq Bhasin,EMP0002,Broadband Maintenance,9434082662,divya03@example.com,Pune,Active
2,Viraj Prakash,EMP0003,Network Support,9852657861,fariq44@example.net,Bengaluru,Inactive
3,Jagat Morar,EMP0004,Broadband Maintenance,9023397543,mborra@example.org,Bengaluru,Inactive
4,Quincy Singh,EMP0005,Field Support,9707922610,rdate@example.net,Chennai,On Leave

In [45]:
engineers_df.to_csv("../data/engineers.csv", index=False)

print("engineers.csv created successfully!")

engineers.csv created successfully!

In [46]:
installation_data = []

for customer in broadband_df.itertuples(index=False):

    request_date = fake.date_time_between(start_date="-2y", end_date="now")

    installation_data.append({
        "customer_id": customer.customer_id,
        "request_date": request_date,
        "installation_address": fake.address().replace("\n", ", "),
        "preferred_date": fake.date_between(start_date="today", end_date="+30d"),
        "assigned_engineer_id": random.randint(1, len(engineers_df)),
        "installation_status": random.choice([
            "Pending",
            "Assigned",
            "Completed",
            "Cancelled"
        ])
    })

installation_df = pd.DataFrame(installation_data)

installation_df.head()

,customer_id,request_date,installation_address,preferred_date,assigned_engineer_id,installation_status
0,CUST01502,2024-10-02 23:22:58,"97/505, Dash Circle, Orai-878534",2026-06-30,55,Pending
1,CUST02587,2026-04-23 11:23:51,"939, Mahajan Circle, Chinsurah 540538",2026-07-09,79,Assigned
2,CUST02654,2025-12-29 05:55:33,"H.No. 02, Sem, Gulbarga-598131",2026-07-28,65,Pending
3,CUST01056,2026-03-13 17:26:39,"60, Gour Path, Karimnagar-969002",2026-07-26,78,Cancelled
4,CUST00706,2025-12-27 11:59:18,"56/61, Sawhney Marg, Nagaon 230566",2026-07-19,2,Assigned

In [47]:
installation_df.to_csv("../data/installation_requests.csv", index=False)

print("installation_requests.csv created successfully!")

installation_requests.csv created successfully!

In [48]:
feedback_data = []

comments = [
    "Excellent service.",
    "Good network coverage.",
    "Installation completed on time.",
    "Customer support was helpful.",
    "Billing issue resolved quickly.",
    "Internet speed is satisfactory.",
    "Frequent call drops.",
    "Very satisfied with the service.",
    "Engineer was professional.",
    "Need improvement in network quality."
]

for request_id, request in enumerate(service_df.itertuples(index=False), start=1):

    if request.status in ["Resolved", "Closed"]:

        feedback_data.append({
            "customer_id": request.customer_id,
            "service_request_id": request_id,
            "rating": random.randint(3, 5),
            "feedback_comments": random.choice(comments),
            "feedback_date": fake.date_time_between(
                start_date=request.request_date,
                end_date="now"
            )
        })

feedback_df = pd.DataFrame(feedback_data)

feedback_df.head()

,customer_id,service_request_id,rating,feedback_comments,feedback_date
0,CUST00001,1,5,Engineer was professional.,2025-09-22 05:35:50
1,CUST00001,2,3,Internet speed is satisfactory.,2025-05-03 13:33:13
2,CUST00002,7,3,Frequent call drops.,2025-06-18 16:47:16
3,CUST00003,8,4,Engineer was professional.,2025-12-03 01:28:09
4,CUST00004,11,4,Frequent call drops.,2026-06-29 13:51:45

In [49]:
feedback_df.to_csv("../data/customer_feedback.csv", index=False)

print("customer_feedback.csv created successfully!")

customer_feedback.csv created successfully!